[project]
name = "siglent-python"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pyqt6>=6.10.1",
    "pyqtgraph>=0.14.0",
]

[tool.setuptools]
packages = ["src"]

[project.scripts]
osc_capture = "capture:main"
osc_replay = "replay:main"
